package_version: 1.0.25
project:
  author: Gert Haegdorens
  author_email: Gert@Haegdorens.com
  description: Program Alex using Flask and Alexa Skills Api
  project_name: flask_ext_ask
  url: https://github.com/changrunner/flask_ext_ask
